#!/bin/bash

build() {
    add_binary "/bin/openssl"
    add_runscript
}

help() {
    cat <<HELPEOF
Use this simple hook in combination with plain dm-crypt to decrypt your keyfile in initramfs
before it is used by the encrypt hook. Decrypts with OpenSSL AES-256-CBC and PBKDF2.
Please note: You should only use this in combination with the keyboard and keymap hooks.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et: